import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="min-h-screen max-w-screen-lg mx-auto px-12 md:px-0  pt-16"
    >
      <body className={`antialiased ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
